### ISSUE TITLE
Crash with sunrise/sunset times

### ISSUE THREAD

**Issue by SKUndef** [hussin/timeboxed-watchface#3]
If you select sunrise/sunset modules, probably because weather provider doesn't return relative data, watchface crashes.

Thanks for your awesome work!

**Comment by hussin** [comment]
Other people reported that too, but I can't reproduce it on my watch or emulators. Do you have access to the pebble sdk? It would help a lot if I could see the logs for the crash.

**Comment by SKUndef** [comment]
Sadly not at the moment, asap i will look at the documentation to setup sdk and try to help you. Thanks!

**Comment by SKUndef** [comment]
By the way, which are the providers for these infos?

**Comment by hussin** [comment]
I get the info from the same weather provider you're using (OpenWeather, Yahoo, WeatherUnderground or Forecast.io)

**Comment by SKUndef** [comment]
I see, so i'm using OpemWeather, if you say that it gives the infos, it's strange..

**Comment by hussin** [comment]
Does it happen right when you save the configs or does it take a couple of seconds to crash?

**Comment by SKUndef** [comment]
It happens just when the watchface reloads its configuration.

**Comment by hussin** [comment]
Hmm, then it seems to be more like a problem when saving the configs, not when trying to retrieve the data from the provider.

**Comment by hussin** [comment]
I figured the issue out. I had a bug on the hour formatting code when leading zero was disabled. I fixed it on v3.8 :)

**Comment by SKUndef** [comment]
Fantastic, thanks! 😄
