### ISSUE TITLE
Request for turning off/on battery status

### ISSUE THREAD

**Issue by TobiasBales** [hussin/timeboxed-watchface#4]
Hey,
for off, I gotta say, I really like timeboxed.
If I could have one wish, it would be to be able to disable the battery status display
(or maybe even hide it until < 15% or so)

If you are interested for the feature but don't want to add it, I could take a look too.

**Comment by hussin** [comment]
Hi! I have plans to make the battery indicator a regular module like the other ones, so this should be done soon :)

**Comment by pcause** [comment]
Also like the watchface a lot.  If you are adding to battery, having time since last charge would be useful.

**Comment by hussin** [comment]
Battery is now a module on v4.0, so you can hide it or replace it with something else :)
