### ISSUE TITLE
display wrong after dismissing the new event popus in version 4

### ISSUE THREAD

**Issue by pcause** [hussin/timeboxed-watchface#6]
I am using a pebble time with version 4+.  this version of pebble pops up a little notification on the bottom of the screen before an event.  when i click back to dismiss the popup the display from the watchface is incorrect.  the battery  level seems gone.  i don't have the "enable quickview"  mode set.  maybe you intend this to be set but the description led me to believe it wasn't needed.

**Comment by hussin** [comment]
Hi! If you have quick mode enabled, this is how it should look like when the notification shows:
![pebble_screenshot_2016-10-07_22-27-43](https://cloud.githubusercontent.com/assets/1525761/19210642/885103d0-8cdd-11e6-8972-c80d1e223bad.png)

And with quickview disabled:
![pebble_screenshot_2016-10-07_22-28-55](https://cloud.githubusercontent.com/assets/1525761/19210645/8f1961ee-8cdd-11e6-8dd4-57c8e76c1a93.png)

In both cases the battery is gone as the display either adjusts for the notification or the notification covers it. You can use it either way depending on your preference. It should go back to the normal state when you click back.

**Comment by pcause** [comment]
thanks.  didn't go back to normal on my watch.  i have the wind direction/speed at bottom right (blank bottom left) and after dismissal it is right under the date and the battery % is missing

**Comment by hussin** [comment]
I was trying to reproduce it and I realized that if you change the settings to disable quick view mode while the notification is up, it won't go back to the default state. Is that your case?

**Comment by pcause** [comment]
nope.  i had the quick mode disabled when i had the issue.  never turned it on at all or changed until after I posted this.

**Comment by pcause** [comment]
I enabled the quick view and all is OK.  if I disable, without any notifications, I get the behavior again.  Just leaving quick view enabled.

**Comment by hussin** [comment]
I finally got to reproduce this and I think I figured it out. A fix will come in the 4.0 release :)

**Comment by hussin** [comment]
Should be fixed now :D
